# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Upload

on:
  push:
    tags:
      - "*.*.*"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  upload:
    needs: [tests]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup VERSION.txt
      run: |
        echo ${{ github.ref_name }} > VERSION.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade twine build

    - name: Build dist
      run: |
        python -m build

    - name: Upload dist
      run: |
        TWINE_USERNAME=${{ secrets.TWINE_USERNAME }} TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }} python -m twine upload --non-interactive --repository ${{ vars.TWINE_REPOSITORY }} dist/*
